fix: Modify omission of change to change ValidatorSet to VoterSet for marverick
line/ostracon pull request #345
Opened 2021-11-17 07:32 UTC by kokeshiM0chi

## Description
Corresponding to the omission of change from the validator set to the voter set during version upgrade work.
This commit change was not reflected.[25fe25c](https://github.com/line/ostracon/commit/25fe25c5a5f92f734b8236007916b065c7bb8494)

This PR is an additional modification of this PR #340

2021-11-17 09:33 UTC, torao approved these changes
LGTM

2021-11-17 10:01 UTC, tnasu requested changes
Could you also update `CONTRIBUTING.md`? Should it change in `./test/maverick/node`? 

https://github.com/line/ostracon/blob/main/CONTRIBUTING.md#maverick

>If you're changing the code in consensus package, please make sure to replicate all the changes in ./test/maverick/consensus. Maverick is a byzantine node used to assert that the validator gets punished for malicious behavior.

2021-11-18 09:37 UTC, kokeshiM0chi commented
@tnasu 
> Could you also update CONTRIBUTING.md? Should it change in ./test/maverick/node?

CONTRIBUTING.md does not need to be changed.

>If you're changing the code in consensus package, please make sure to replicate all the changes in ./test/maverick/consensus. Maverick is a byzantine node used to assert that the validator gets punished for malicious behavior.

It means that the code change in consensus package should be applied to this path `./test/maverick/consensus` as well, so I think there is no problem with the previous #340 and current this PR.

2021-11-19 01:56 UTC, tnasu commented
Sorry for my misleading. I mean that I want to change the sentence to the below:

>If you're changing the code in consensus or node package, please make sure to replicate all the changes in  ./test/maverick/consensus and ./test/maverick/node. Maverick is a byzantine node used to assert that the validator gets punished for malicious behavior.

2021-11-19 02:04 UTC, kokeshiM0chi commented
@tnasu 
OK. I will fix it.

2021-11-19 03:01 UTC, tnasu approved these changes

2021-11-19 03:57 UTC, torao approved these changes

2021-11-19 04:10 UTC, merged