Add error handling in newHashKey
line/ostracon pull request #499
Opened 2022-11-14 09:18 UTC by Mdaiki0730

## Description

2022-11-22 03:11 UTC, torao commented
Separating certain functions into a package for the purpose of passing coverage seems to me to be out of line with module design and doesn't seem to be a good idea. And I'm also concerned about the project-local implicit rules that arise.

* What was the key point of the problems
* What options were available
* What were the considerations
* Then, why did you decide this was the best approach?

2022-11-22 03:16 UTC, torao requested changes

2022-11-22 03:16 UTC, torao commented on libs/std/crypto/rand/rand.go
> +package rand
No one looking at the source would know why this function is separated in this package. Any purpose or intent that can only be recognized outside of the source code should be noted in the comment.

2022-11-22 04:34 UTC, Mdaiki0730 commented
After thinking about the following, I am implementing it now.
- Problem: Error handling of crand.Read in newHashKey provides insufficient coverage, but it is difficult to write tests for it. 
- Options:
  - Ignore coverage → The convention of merging after all green is broken
  - Wrap crand.Read as a private function → A wrapper just for testing the standard package is born
  - Wrap crand.Read as public function in libs → Allows aggregation of packages that wrap functions for which test is essentially unnecessary


The current option is selected because the layer where the error occurs is not at the application level but is connected to the test ignore.
I would like to hear your opinion if there are better options for this.

2022-11-24 09:35 UTC, torao commented
@Mdaiki0730 
Looking for other code that uses `crand.Read()`, There is a function `CRandBytes()` in `crypto/random.go` that could be used for this purpose. It may work the same as the current `newHashKey()`, so how about using this instead of creating a specific package?

https://github.com/line/ostracon/blob/main/crypto/random.go#L9-L22

2022-11-24 09:52 UTC, Mdaiki0730 commented
I think very good@@
Thank you for finding this function!

2022-11-24 10:22 UTC, Mdaiki0730 commented
I created another PR because we found a completely different solution than the this PR.
New One: https://github.com/line/ostracon/pull/509

2022-11-24 10:22 UTC, closed without merging